//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tapeando.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TapeandoContext : DbContext
    {
        public TapeandoContext()
            : base("name=TapeandoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Place> tbl_places { get; set; }
        public DbSet<Tapa> tbl_tapas { get; set; }
        public DbSet<TempTest> tbl_temp_test { get; set; }
    }
}
